# Generated by Django 4.1.6 on 2023-02-13 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='foods',
            field=models.ManyToManyField(to='api.food'),
        ),
    ]
