# Generated by Django 4.1.6 on 2023-02-17 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_meal_foods'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='time',
        ),
    ]
