# Generated by Django 4.1.6 on 2023-02-17 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_meal_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='meal',
            field=models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner')], default='breakfast', max_length=100),
        ),
        migrations.DeleteModel(
            name='Meal',
        ),
    ]
